services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgresql://xsspecter:xsspecter@db:5432/xsspecter_db?schema=public
    depends_on:
      - db
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: .
          ignore:
            - node_modules
            - package-lock.json
          target: /app/
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: ./.env
          target: /app/
    env_file:
      - ./.env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=xsspecter
      - POSTGRES_PASSWORD=xsspecter
      - POSTGRES_DB=xsspecter_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: